name = "kv"
main = "src/index.ts"
compatibility_date = "2024-12-12"
env = { }
kv_namespaces = [
    { binding = "KV", id = "50e5446363274bb1aad2d00522f43633" }
]

[observability]
enabled = true
head_sampling_rate = 1